# Generated by Django 6.0 on 2025-12-14 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('date_of_issue', models.DateField()),
                ('issued_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('client', 'Клиент')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('Number_of_phone', models.CharField(max_length=11)),
                ('Date_of_birth', models.DateField()),
                ('Discount', models.IntegerField()),
                ('Document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='hotel.document')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival_date', models.DateField()),
                ('Departure_date', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Paid_fact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Date_of_provision', models.DateField()),
                ('Booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='hotel.booking')),
                ('Service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='hotel.service')),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor', models.IntegerField()),
                ('Quantity_room', models.IntegerField()),
                ('Quantity_bed', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='hotel.category')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.suite'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.guest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='hotel.category')),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='hotel.item')),
            ],
            options={
                'unique_together': {('Category_id', 'Item_id')},
            },
        ),
    ]
